qube_version: '2.6.1 # <<QUBE_NO_BUMP>>'
full_name: Steffen Greiner
email: Steffen.Greiner@uni-tuebingen.de
project_name: xml-manager-lib
project_short_description: 'library for reading and writing of specific openBIS xml
  properties '
version: 1.6.0-SNAPSHOT
domain: lib
language: groovy
project_slug: xml-manager-lib
project_slug_no_hyphen: xml_manager_lib
template_version: '1.0.1 # <<QUBE_NO_BUMP>>'
template_handle: lib-groovy
github_username: steffengreiner
creator_github_username: steffengreiner
is_github_repo: false
is_repo_private: false
is_github_orga: false
copyright_holder: QBiC
license: MIT
