//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.22 at 04:15:01 PM CEST 
//


package life.qbic.xml.study;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the life.qbic.xml.study package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: life.qbic.xml.study
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Qexperiment }
     * 
     */
    public Qexperiment createQexperiment() {
        return new Qexperiment();
    }

    /**
     * Create an instance of {@link TechnologyType }
     * 
     */
    public TechnologyType createTechnologyType() {
        return new TechnologyType();
    }

    /**
     * Create an instance of {@link Qfactors }
     * 
     */
    public Qfactors createQfactors() {
        return new Qfactors();
    }

    /**
     * Create an instance of {@link Qproperty }
     * 
     */
    public Qproperty createQproperty() {
        return new Qproperty();
    }

    /**
     * Create an instance of {@link Qcategorical }
     * 
     */
    public Qcategorical createQcategorical() {
        return new Qcategorical();
    }

    /**
     * Create an instance of {@link Qcontinuous }
     * 
     */
    public Qcontinuous createQcontinuous() {
        return new Qcontinuous();
    }

    /**
     * Create an instance of {@link Qcontlevel }
     * 
     */
    public Qcontlevel createQcontlevel() {
        return new Qcontlevel();
    }

    /**
     * Create an instance of {@link Qcatlevel }
     * 
     */
    public Qcatlevel createQcatlevel() {
        return new Qcatlevel();
    }

}
